### ISSUE TITLE
Residuewise dihedral entropy

### ISSUE THREAD

**Issue by andresilvapimentel** [liedllab/X-Entropy#54]
Hi Patrick, Congratulation on the paper publixhed in JCIM.
Please, let me know how you generated Figure 3 for 1 ms trajectory projected onto the molecular structure
of BPTI.
Could you share the ipynb notebook, please? 
Thank you very much. Regards, Andre Pimentel

**Comment by jokr91** [comment]
Hi Andre Pimentel,

As far as I know, this is done in combination with PyMol, therefore, a simple notebook would not be sufficient.
In PyMol, you can color the residues according to their b-factor. If you replace the b-factor of your structure with the dihedral entropy, you can easily create a picture similar to that one.

Pinging @askamenik since she made that particular picture. Anna please correct me if I am wrong, or if you have any additional information.

Best, Johannes

**Comment by askamenik** [comment]
Yes, I made that figure using pymol, using the following tutorial from the pymolwiki:
https://pymolwiki.org/index.php/Color
see section "Reassigning B-Factors and Coloring"
So for this you would need to read in a single-column file where the entropy for each residue is stored - which you can get quite easily from X-Entropy.

Let me know if you need more help on that matter!

On a different note, you could probably also do it in a notebook using eg nglview, but I am no expert in that...

**Comment by andresilvapimentel** [comment]
Dear Anna,
I tried to use the X-Entropy using the trajectory xtc file from a MD
simulation performed by gronmacs. It did not work it.
Then, I tried to use MDAnalysis to convert the xtc file to a numpy file,
but it did not work as well.
The program stops running on dih_ent = dihedrals.dihedralEntropy(data=data,
verbose =true). The error is:
Suspicious data shape...
No weight been given.
TypeError: ufunc 'isfinite' not supported for the input types, and the
inputs could not be safely coerced to any supported types according to the
casting rule "safe"

Could you help me to understand the exact procedure to execute the
x-entropy, please?

Thanks.

Em sex, 14 de mai de 2021 11:17, Anna Sophia Kamenik <
***@***.***> escreveu:

**Comment by askamenik** [comment]
Hi Andre,

so from what you are describing it sounds like you are trying to feed in the raw coordinates of the trajectory, is that correct?
If so, that's a problem an will most likely not work. X-Entropy is intended to calculate entropies from specific observables, such as dihedrals. So you need to calculate the dihedrals beforehand, eg with mdanalysis, cpptraj, pytraj or loos, etc. 
And then you can reand in these data, feed it to X-entropy and learn something about the flexibility of your protein.

Best,
Anna

**Comment by andresilvapimentel** [comment]
Yes, that's correct
One more question... Could I use the file with only the backbone info or
with the whole molecule information?
Thanks

Em qua, 2 de jun de 2021 18:44, Anna Sophia Kamenik <
***@***.***> escreveu:

**Comment by askamenik** [comment]
so to preprocess input data for X-entropy, eg by calculating backbone dihedrals using cpptraj/mdanalysis/mdtraj/loos/etc. you can use the backbone trajectory.

But once again - you cannot directly pass the coordinates of your simulation to X-entropy, you need to precalculate the time-evolution of your dihedrals.

Best
Anna

**Comment by andresilvapimentel** [comment]
Thank you, Anna. I think I am almost there... One more question... I have
the following code:

traj = mdtraj.load('ATN_161.xtc',top='ATN_161.pdb')

phi_atom_inds, phi_angles = geometry.dihedral.compute_phi(traj)
psi_atom_inds, psi_angles = geometry.dihedral.compute_psi(traj)
print(phi_angles.shape, psi_angles.shape)
(2501, 4) (2501, 4)
data = np.concatenate((phi_angles, psi_angles), axis=1)
print(data.shape)
(2501, 8)
dih_ent = dihedrals.dihedralEntropy(data=data,verbose=True)
dih_ent.calculate()
Warning:

Found multiple data sets. Applying rule of thumb on all, and take the
maximum resolution estimated.
No weights been given.
Initializing C++ kernel for kde...

/usr/local/lib/python3.7/site-packages/xentropy/internal/pre_post_processing.py:133:
RuntimeWarning: Your input data has suspicious shape. First dim is
expected to be smaller than second dim. Data should have shape:
(N_features, N_frames).
  warnings.warn(warn_msg, RuntimeWarning)  # potentially transposed data

KDE finished.

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83:
VisibleDeprecationWarning: Creating an ndarray from ragged nested
sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays
with different lengths or shapes) is deprecated. If you meant to do
this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

array([15.4597707 , 15.41532891, 15.4496718 , ..., 15.48540527,
       15.50224726, 15.43976968])

S = dih_ent.entropy
S
array([15.4597707 , 15.41532891, 15.4496718 , ..., 15.48540527,
15.50224726, 15.43976968]) S.shape (2501,)
Later, when I plot the xs, ys arrays, I found the error: unsupported format
string passed to numpy.ndarray.__format__
I think I am doing something wrong with the data input file. Please, let me
know what I am doing wrong. Thank you in advance...



Em qui., 3 de jun. de 2021 às 05:38, Anna Sophia Kamenik <
***@***.***> escreveu:

**Comment by jokr91** [comment]
Hi Andre,

Considering ATN 161, I would assume that you have 2501 frames and 8 dihedrals (4 phi + 4 psi). With this assumption, your data structure is (N_frames, N_features). The library however expects (N_features, N_frames), this is also why you get the "suspicious shape" warning. All you need to do is transpose your input data, so that it is of shape (N_features, N_frames), instead of (N_frames, N_features).

Hope this helps,
Johannes

**Comment by andresilvapimentel** [comment]
Thanks.
I found a S array (shape 8). See below...

dih_ent = dihedrals.dihedralEntropy(data=data,verbose=True)
dih_ent.calculate()

Found multiple data sets. Applying rule of thumb on all, and take the
maximum resolution estimated.
No weights been given.
Initializing C++ kernel for kde...
KDE finished.

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83:
VisibleDeprecationWarning: Creating an ndarray from ragged nested
sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays
with different lengths or shapes) is deprecated. If you meant to do
this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)

array([ 2.3964176 , 11.91205745,  8.08232971,  4.88948935,  1.59430858,
        6.29305316, 10.84859829, 12.15798179])

Is that correct? One for each dihedral angle?

Also... When I plotted the probability density data, I found that the
histograms are not matching the X-Entropy KDEs. Is that correct?

I plotted the data using the code below:
f,axs = plt.subplots(2,4,figsize=(10,6),sharex=True,sharey=True)


for ax,dat,xs,ys,S in zip
(axs.flatten(),data,dih_ent.pdf_x_deg,dih_ent.pdf_deg, dih_ent.entropy):
    ax.hist(dat,180,density=True, label="histogram")
    ax.plot(xs,ys, lw=5,alpha=.7, label="XEntropy KDE\nS = {:.3f} J/(mol*K)"
.format(S))

    ax.set(xlabel="artificial dihedrals", ylabel="probability density")
    ax.legend()
f.tight_layout()
What can I do to get a better result and plot?

[image: image.png]



Em sáb., 5 de jun. de 2021 às 12:56, Johannes Kraml <
***@***.***> escreveu:

**Comment by jokr91** [comment]
One entropy for each dihedral is fine.

To your other problem, could you maybe send me either the dihedral data, or some figures, so that I can figure out what is going on and what exactly you mean by "not matching".
Thanks,
Johannes

**Comment by andresilvapimentel** [comment]
[data.zip](https://github.com/liedllab/X-Entropy/files/6610453/data.zip)
Here is the data.

**Comment by andresilvapimentel** [comment]
[figures.docx](https://github.com/liedllab/X-Entropy/files/6610482/figures.docx)
Here are the figures.

**Comment by jokr91** [comment]
So it seems you are plotting the histogram in radians, while plotting the PDF in degrees, if you plot both in radians, it should be fine.

If not, please contact me again.

Thanks

**Comment by andresilvapimentel** [comment]
I plotted using this code:
f,axs = plt.subplots(2,4,figsize=(10,6),sharex=True,sharey=True)

for ax,dat,xs,ys,S in zip
(axs.flatten(),data,dih_ent.pdf_x_deg,dih_ent.pdf_deg, dih_ent.entropy):
    ax.hist(dat,180,density=True, label="histogram")
    ax.plot(xs,ys, lw=5,alpha=.7, label="XEntropy KDE\nS = {:.3f} J/(mol*K)"
.format(S))

    ax.set(xlabel="artificial dihedrals", ylabel="probability density")
    ax.legend()
f.tight_layout()

and also using this code:
f,axs = plt.subplots(2,4,figsize=(10,6),sharex=True,sharey=True)

for ax,dat,xs,ys,S in zip
(axs.flatten(),data,dih_ent.pdf_x_deg,dih_ent.pdf_deg, dih_ent.entropy):
    ax.hist(dat/180*np.pi,180,density=True, label="histogram")
    ax.plot(xs,ys, lw=5,alpha=.7, label="XEntropy KDE\nS = {:.3f} J/(mol*K)"
.format(S))

    ax.set(xlabel="artificial dihedrals", ylabel="probability density")
    ax.legend()
f.tight_layout()
It did not work with both codes. Please, let me know what I am doing wrong.

Em seg., 7 de jun. de 2021 às 13:15, Johannes Kraml <
***@***.***> escreveu:

**Comment by andresilvapimentel** [comment]
I got it. Thanks. It worked fine!!!

Em seg., 7 de jun. de 2021 às 17:48, Andre Pimentel ***@***.***>
escreveu:

**Comment by jokr91** [comment]
perfect, thanks
