### ISSUE TITLE
Very low values in weights array leads to RuntimeError: Unknown exception

### ISSUE THREAD

**Issue by xctat** [liedllab/X-Entropy#57]
Entropy calculation reports 'Unknown exception' with small weights.

details: dihedrals.dihedralEntropy() reports error with weights around 1e-30, multiplying the values by 1e3 solve the issue. (Multiplying by anything lower doesn't work. X-Entropy installation followed the standard procedure with conda.)

Error message
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<'ipython-input-79-f0c02d38a1ab> in <'module>
      2 dih_ent = dihedrals.dihedralEntropy(data=torsions, 
      3  weights=pop_norm.values, verbose=True)
----> 4 dih_ent.calculate()
~/.conda/envs/p3/lib/python3.8/site-packages/xentropy/dihedrals.py in calculate(self, resolution, method, verbose, id_gas)
    118 
    119             # integral = kernel.integrate(start, end, method=self.method)
--> 120             p_logp = kernel.calculate_entropy(-PI, PI, method=self.method)
    121 
    122             entropy = - p_logp * id_gas

xentropy/kde_kernel/kde_kernel.pyx in xentropy.kde_kernel._kde_kernel.calculate_entropy()

RuntimeError: Unknown exception

**Comment by xctat** [comment]
the lowest value for individual weight goes to 1e-70

**Comment by Clownshift** [comment]
This is related to the dihehedralEntropy module.
However, I believe that this might lead to issue for the kde module as well. There we might have a general problem with the weighted kde anyways, though #56 .

@jokr91 I can easily set *very low* weights to zero in the python frontend (then I would give a warning, that we do this manipulation to the input values)
Anyways, is it possible to trace way this exception is *unknown*?

**Comment by Clownshift** [comment]
Actually, I think the problem may lie elsewhere, because the values do not really need to be very small even. 
However, the problem might be connected to the normalization of the weights (#56 )

![Screenshot from 2021-10-01 15-29-46](https://user-images.githubusercontent.com/20798138/135628214-f92e550f-e891-486b-8e51-62b05f4cee7b.png)

**Comment by Clownshift** [comment]
I suggest to pull  #60 first as soon as it is accepted.
